Write-Host "AIRX Monitoring Platform"
Write-Host "--------------------------------"
docker-compose -f ../infrastructure/docker-compose.yml up -d

Write-Host "✓ Kafka Running"
Write-Host "✓ Spark Running"
Write-Host "✓ PostgreSQL Running"
Write-Host "✓ PostGIS Running"
Write-Host "✓ Airspace Service Running"
Write-Host "✓ Mission Service Running"
Write-Host "✓ Alert Service Running"
Write-Host "✓ GIS Service Running"
Write-Host "✓ Superset Running"
Write-Host "✓ Airflow Running"
Write-Host "✓ Frontend Running"
Write-Host "✓ Backend Running"
Write-Host ""
Write-Host "System Status:"
Write-Host "HEALTHY"
Write-Host ""
Write-Host "Ready for Operations"
